### PR TITLE
Fix bug with infinite loop of authorization ajax calls

### PR DESCRIPTION
**Pull request by robinbortlik**
- task: https://reevoo.atlassian.net/browse/TOOL-4
- in the case that user has no permission to access API endpoint, the response status is 401 which invoke the callback which refresh token and repeat previous ajax call. But in this case, the API return again the 401.
- the maximum count of ajax call repeatiton is set to 5. If the count exceed, the user is redirected to login page.

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
*If you're new, read the [guidelines]
(https://github.com/reevoo/guidelines/blob/master/pull_requests.md).*

Good code is **tested**, **designed for change**, **easy to understand**
and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [ ] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need
tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [ ] The code is well-designed and able to cope with change.
- [ ] The code is easy to understand.
- [ ] Tests cover happy and unhappy paths in the code.
- [ ] Tests are green on CI (or pulled/tested on your machine).

**Comment by mhenrixon** [comment]
LGTMBWTFDIK!

**Comment by irikuo** [comment]
I have a hard time trying to understand the problem. Well, not the problem, what I don't understand is why we can't distinguish between permission denied and token expired. I agree both are "Permission denied" at a high level, but we should have a mechanism to avoid things like this.

If we can't tell from the backend somehow the difference and we don't have any other option than doing what the code in here is doing, I would reduce the counter to 2. It doesn't look like repeating the request more times would change anything.

But maybe I am not fully understanding the scope of the problem.

**Comment by seddy** [comment]
LGTM - @irikuo that is indeed the problem, the root cause is that the server may return a `401` when it should be returning a `403` if the user is not allowed to make a particular request.  This is due to a bug in the client_portal-api_client gem, which will need to be fixed later (@robinbortlik has already raised another ticket about this).

I'm happy lowering number of retires to 2 as it's a good point that if we fail twice, it's unlikely to improve - but this is such an edge case that 5 is probably fine as well.  Up to you @robinbortlik :)

**Comment by robinbortlik** [comment]
@irikuo Well, I completely understand. The issue is, we currently can't distinguish between "Not Authorized" and "Permission Denied". There is a task created to fix it. https://reevoo.atlassian.net/browse/TOOL-20

But still, there can be the another situations where the API can return 401. Please see https://github.com/reevoo/client_portal_api_client_gem/blob/master/lib/client_portal_api_client/user.rb#L22 

And I would like to avoid, the situation, that client will trigger hundreds of requests and overload our server, just because somewhere is a mistake.

**Comment by irikuo** [comment]
Thanks guys. Knowing the context and that we have a plan to fix the API, I am more than happy to roll with this for now.

So... LGTM 👍

**Pull request merged**
